package router

import (
	"schoolmanagement/internal/di"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "schoolmanagement/docs" // This will be generated by swag init
)

func InitRouter() *gin.Engine {
	container := di.NewContainer()
	router := gin.Default()

	// Swagger UI route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.Use(cors.New(cors.Config{
		AllowOrigins: []string{
			"*",
			"http://localhost:3000",      // Para acesso local via localhost
			"http://192.168.18.153:3000", // Para acesso via IP na rede local
			"http://192.168.18.190:3000", // Para acesso via IP na rede local
		},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	api := router.Group("/api/v1")

	SetupAuthRoutes(api, container)
	SetupUserRoutes(api, container)
	SetupActivityRoutes(api, container)
	SetupTeacherRoutes(api, container)

	return router
}
